version: '3.8'

services:

  db:
    container_name: "${COMPOSE_PROJECT_NAME}_db"
    image: skazuki/alpine-mongodb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_HOST: '%'
    env_file:
    - .env
    volumes:
    - ./db:/data/db

  server:
    container_name: "${COMPOSE_PROJECT_NAME}_server"
    image: altv/server:custom
    build: .docker
    restart: unless-stopped
    depends_on:
    - db
    ports:
    - '2789:2789'
    - '2789:2789/udp'
    volumes:
    - ./server.cfg:/altv/server.cfg
    - ./package.json:/altv/package.json
    - ./package-lock.json:/altv/package-lock.json
    - ./node_modules:/altv/node_modules
    - ./resources:/altv/resources
